name: PR validator

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'assets/**'
  push:
    branches:
      - main
    paths-ignore:
      - 'assets/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g twilio-cli
      - run: twilio plugins:install @twilio-labs/plugin-flex
      - run: npm install
      - run: npm test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}